package com.web.spirder.demo.web.dto.system;


import com.fasterxml.jackson.annotation.JsonFormat;
import com.idaoben.utils.dto_assembler.annotation.EnableAssembling;
import com.idaoben.utils.dto_assembler.annotation.Mapping;
import com.idaoben.utils.dto_assembler.annotation.TypeMapping;
import com.web.spirder.demo.dao.entity.Role;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Set;

/**
 *
 * 角色 Dto接口
 * Generated by DAOBEN CODE GENERATOR
 * @author  Daoben Code Generator
 */
@ApiModel
@EnableAssembling(mappings = @TypeMapping(from = Role.class))
public interface RoleDto {

    @ApiModelProperty("ID")
    @Mapping
    @JsonFormat(shape = JsonFormat.Shape.STRING) Long getId();

    @ApiModelProperty("角色名")
    @Mapping
    String getRoleName();

    @ApiModelProperty("编码")
    @Mapping
    String getCodeNo();

    @ApiModelProperty("是否启用")
    @Mapping
    boolean getEnabled();

    @ApiModelProperty("显示的顺序号，用于排序显示")
    @Mapping
    Integer getDisplayOrder();

    @ApiModelProperty("备注")
    @Mapping
    String getRemark();

    @ApiModelProperty(value = "角色权限集")
    @Mapping
    Set<String> getPermissions();
}