package com.web.spirder.demo.dao.repository;

import com.idaoben.web.common.dao.BaseRepository;
import com.web.spirder.demo.dao.entity.Role;

/**
*
* 角色 Dao接口
* Generated by DAOBEN CODE GENERATOR
* @author  Daoben Code Generator
*/
public interface RoleRepository extends BaseRepository<Role, Long> {
}